# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd757e919d039eb0b89ac4eae6455097c29ecc43404dc18258755cfccf1acff50fcffa2c9a69bad291c498dee2968e2d066cc4e53377984cfb902f04fd49c85

test:
  secret_key_base: ab091c1acc25bdd6f495277e66d586fca41ef7ea713246a7f4f4c116f95b3bfb13cc109a8b45514f1d11f096a479b64e39cc6a3a08c9c0027950493c5fdd6675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
